task: mdm
gpus: [0]
exp_name: 'atm_uestc'

# module path
network_module: lib.networks.mdm.network
loss_module: lib.train.losses.mdm
evaluator_module: lib.evaluators.mdm
visualizer_module: lib.visualizers.mdm

arch: trans_enc
batch_size: 64
cond_mask_prob: 0.0
cuda: true
data_dir: ''
dataset: uestc
device: 2
diffusion_steps: 1000
emb_trans_dec: false
eval_batch_size: 32
eval_during_training: false
eval_num_samples: 1000
eval_rep_times: 3
eval_split: test
lambda_fc: 1.0
lambda_rcxyz: 1.0
lambda_vel: 1.0
latent_dim: 512
layers: 8
log_interval: 1000
lr: 0.0001
lr_anneal_steps: 0
noise_schedule: cosine
num_frames: 60
num_steps: 600000
overwrite: true
resume_checkpoint: ''
save_dir: save/atm_uestc
save_interval: 50000
seed: 10
sigma_small: true
train_platform_type: TensorboardPlatform
unconstrained: false
weight_decay: 0.0
