task: kit
gpus: [0]
exp_name: 'kit'
dataset_name: 'kit'

# module path
train_dataset_module: lib.datasets.mdm.synthetic 
test_dataset_module: lib.datasets.mdm.synthetic
network_module: lib.networks.mdm.network
loss_module: lib.train.losses.mdm
evaluator_module: lib.evaluators.mdm
visualizer_module: lib.visualizers.mdm

network:
    legacy: False
    modeltype: ''
    njoints: 251
    nfeats: 1
    num_actions: 1
    data_rep: 'hml_vec'
    dataset: 'kit'

    pose_rep: 'rot6d'
    glob: True
    glob_rot: True
    translation: True

    latent_dim: 512

    ff_size: 1024
    num_layers: 8
    num_heads: 4
    dropout: 0.1

    activation: 'gelu'
    clip_dim: 512
    action_emb: 'tensor'
    arch: 'trans_enc'

    cond_mode: 'text'
    cond_mask_prob: .1

    emb_trans_dec: False

    clip_version: 'ViT-B/32'


diffusion: 
    diffusion_steps: 1000
    noise_schedule: 'cosine'
    sigma_small: True

    lambda_rcxyz: 0.0
    lambda_vel: 0.0
    lambda_fc: 0.0

train_dataset:
    mode: "train"
    data_root: 'data/KIT-ML'
    split: 'train'
    motion_dir: 'new_joint_vecs'
    text_dir: 'texts'
    mean: 'Mean.npy'
    std: 'Std.npy'
    joints_num: 22
    dim_pose: 251
    max_motion_length: 196
    max_text_len: 20
    unit_length: 4

eval_dataset:
    mode: "eval"
    data_root: 'data/KIT-ML'
    meta_root: 'data'
    split: 'test'
    motion_dir: 'new_joint_vecs'
    text_dir: 'texts'
    mean: 'Mean.npy'
    std: 'Std.npy'
    mean_eval: 'kit_mean.npy'
    std_eval: 'kit_std.npy'
    joints_num: 22
    dim_pose: 251
    max_motion_length: 196
    max_text_len: 20
    unit_length: 4

gt_dataset:
    mode: "gt"
    data_root: 'data/KIT-ML'
    meta_root: 'data'
    split: 'test'
    motion_dir: 'new_joint_vecs'
    text_dir: 'texts'
    mean: 'kit_mean.npy'
    std: 'kit_std.npy'
    joints_num: 22
    dim_pose: 251
    max_motion_length: 196
    max_text_len: 20
    unit_length: 4

test_dataset:
    mode: "test"
    data_root: 'data/KIT-ML'
    split: 'test'
    motion_dir: 'new_joint_vecs'
    text_dir: 'texts'
    mean: 'Mean.npy'
    std: 'Std.npy'
    joints_num: 22
    dim_pose: 251
    max_motion_length: 196
    max_text_len: 20
    unit_length: 4

train:
    batch_size: 64
    optim: "adam"
    lr: 1e-4
    resume_checkpoint: ""
    use_fp16: False
    fp16_scale_growth: 1e-3
    weight_decay: 0.0
    lr_anneal_steps: 0
    num_steps: 600000
    sheduler: 
        type: 'exponential'
        gamma: 0.1
        decay_epochs: 1000
    collator: "t2m_collate"

test:
    batch_size: 32

eval:
    eval_rep_times: 3
    eval_batch_size: 32
    eval_num_samples: 1000
    collator: "t2m_eval_collate"

ep_iter: 500
save_ep: 20
eval_ep: 1      
save_latest_ep: 5 
log_interval: 100

eval_log_path: "data/eval_log"